Lesson.register({
  id: 'blogs',
  title: 'Engineering blogs and papers',
  minutes: 6,
  summary: `The course teaches the building blocks. Engineering blogs show how real companies used them, and what broke. During Phase 8, read one post a week, and later redraw the architecture from memory.`,
  blocks: [
    { type: 'callout', tone: 'analogy', title: 'In simple words', html: `Engineers at big companies write about their own mistakes and solutions and share them. These are called <strong>engineering blogs</strong>. They are free, and the most real learning is found here: "we thought this, this broke, then we did this".<br><br>Read one post a week from the list below. If you do not understand everything at first, that is fine. As the course goes on, the posts will feel easier.` },
    { type: 'callout', tone: 'term', title: 'New word: Engineering blog and paper', html: `<strong>Engineering blog:</strong> articles written by a company's engineers, like "How Discord stores trillions of messages".<br><strong>Paper:</strong> a longer, research-style document, often published at a conference, like Amazon's Dynamo paper. A bit heavy, but the foundation of the whole industry.` },
    { type: 'h2', text: 'How to read a post' },
    { type: 'steps', items: [
      { t: 'Read the problem first, not the solution', d: 'Read the introduction and stop. Write on paper how you would solve this problem.' },
      { t: 'Then read the whole post, and note 3 things', d: '1) Which constraint (limit) forced their choice? 2) Which trade-off did they accept? 3) What would they do differently if they did it again?' },
      { t: 'Redraw it from memory', d: 'The next day, draw the architecture diagram without looking. The box you forgot is your next revision.' },
    ]},
    { type: 'callout', tone: 'warn', html: `Engineering posts get old. A post from 2015 is the truth of that time, not of today. Always check the date, and ask yourself whether their problem is still the same today.` },

    { type: 'h2', text: 'Newsletters and explainers' },
    { type: 'links', items: [
      ['ByteByteGo (Alex Xu)', 'Short, visual explanations and real architectures', 'https://blog.bytebytego.com'],
      ['AlgoMaster Newsletter', 'Beginner-friendly deep dives into concepts, and interview tips', 'https://blog.algomaster.io'],
      ['High Scalability', 'The classic archive of "how X scaled"', 'http://highscalability.com'],
      ['The Pragmatic Engineer', 'How big tech systems run on the inside', 'https://newsletter.pragmaticengineer.com'],
      ['Martin Fowler', 'Microservices, CQRS, event sourcing, sagas', 'https://martinfowler.com'],
      ['All Things Distributed', 'The distributed systems blog of Amazon\'s CTO (from the team behind Dynamo and S3)', 'https://www.allthingsdistributed.com'],
      ['AWS Architecture Blog', 'Reference architectures', 'https://aws.amazon.com/blogs/architecture'],
    ]},
    { type: 'h2', text: 'Global engineering blogs' },
    { type: 'links', items: [
      ['Netflix TechBlog', 'Streaming at scale, chaos engineering', 'https://netflixtechblog.com'],
      ['Uber Engineering', 'H3 geo index, real-time matching', 'https://www.uber.com/blog/engineering'],
      ['Meta Engineering', 'Planet-scale caching, social graph', 'https://engineering.fb.com'],
      ['Discord', 'Trillions of chat messages', 'https://discord.com/blog'],
      ['Cloudflare', 'Networking, CDN, DDoS, edge', 'https://blog.cloudflare.com'],
      ['Slack Engineering', 'Real-time messaging, Vitess', 'https://slack.engineering'],
      ['Stripe', 'Payments reliability, idempotency', 'https://stripe.com/blog/engineering'],
      ['Dropbox Tech', 'File sync engines', 'https://dropbox.tech'],
      ['Airbnb Engineering', 'Search, payments, moving to services', 'https://medium.com/airbnb-engineering'],
      ['LinkedIn Engineering', 'Where Kafka was born', 'https://www.linkedin.com/blog/engineering'],
      ['Pinterest Engineering', 'Feeds, MySQL sharding, recommendations', 'https://medium.com/pinterest-engineering'],
      ['Shopify Engineering', 'Flash sales, modular monolith', 'https://shopify.engineering'],
      ['Google Research', 'The ideas behind GFS, MapReduce, Bigtable and Spanner', 'https://research.google/blog'],
    ]},
    { type: 'h2', text: 'Indian engineering blogs' },
    { type: 'links', items: [
      ['Hotstar / JioHotstar', 'Tens of millions of viewers at once, the traffic "tsunami"', 'https://blog.hotstar.com'],
      ['Swiggy Bytes', 'Dispatch, ETAs, peak-hour scaling', 'https://bytes.swiggy.com'],
      ['Zomato', 'New Year\'s Eve order peaks', 'https://blog.zomato.com'],
      ['Razorpay Engineering', 'Payments, UPI, idempotency', 'https://engineering.razorpay.com'],
      ['Zerodha Tech', 'A small team, practical "boring" tech', 'https://zerodha.tech'],
      ['Flipkart Tech', 'Big Billion Days traffic', 'https://blog.flipkart.tech'],
      ['PhonePe Tech', 'UPI at massive volume', 'https://tech.phonepe.com'],
    ]},
    { type: 'h2', text: 'Must-read posts and papers' },
    { type: 'table', head: ['Title', 'Source', 'What it teaches'], rows: [
      ['Scaling Is Not An Accident; T for Tsunami', 'Hotstar', 'Scaling up ahead of time for live cricket (not relying on autoscaling)'],
      ['How Discord Stores Trillions of Messages', 'Discord', 'Chat storage, Cassandra to ScyllaDB, hot partitions'],
      ['H3: Uber\'s Hexagonal Hierarchical Spatial Index', 'Uber', '"Drivers near me"'],
      ['Sharding & IDs at Instagram', 'Instagram', 'Postgres sharding, time-sortable IDs'],
      ['Announcing Snowflake', 'Twitter', 'Distributed unique IDs'],
      ['Designing Robust and Predictable APIs with Idempotency', 'Stripe', 'Safe retries'],
      ['How Figma\'s Multiplayer Technology Works', 'Figma', 'Real-time collaboration, resolving conflicts'],
      ['Rewriting the Heart of Our Sync Engine', 'Dropbox', 'File sync design'],
      ['Scaling Datastores at Slack with Vitess', 'Slack', 'MySQL sharding'],
      ['Dynamo: Amazon\'s Highly Available Key-Value Store', 'Amazon, 2007', 'Consistent hashing, quorums'],
      ['Scaling Memcache at Facebook', 'Meta, NSDI 2013', 'Caching, thundering herds'],
      ['GFS, MapReduce, Bigtable', 'Google papers', 'The foundation of storage and batch processing'],
      ['Kafka: a Distributed Messaging System for Log Processing', 'LinkedIn, 2011', 'Queue vs log'],
    ], caption: 'Search for these titles; each one is linked to a station of the roadmap. The papers are from 2007-2013: the ideas are still alive today, but the implementation details have changed.' },
    { type: 'p', html: `Where to start? Along with Phase 2, read the Discord and Instagram posts (short and clear). Along with Phase 8, read Hotstar, Uber and Figma. Read the papers (Dynamo, Memcache) after Phase 3, once consistency and quorums make sense.` },
  ],
});
