Lesson.register({
  id: 'blogs',
  title: 'Engineering blogs aur papers',
  minutes: 6,
  summary: `Course building blocks sikhata hai. Engineering blogs dikhate hain ki asli companies ne unhe kaise use kiya, aur kya toota. Phase 8 ke dauran hafte mein ek post padho, aur baad mein architecture memory se redraw karo.`,
  blocks: [
    { type: 'callout', tone: 'analogy', title: 'Seedhi baat', html: `Badi companies ke engineers apni galtiyan aur solutions khud likh ke share karte hain. Inhe <strong>engineering blogs</strong> kehte hain. Ye free hain, aur sabse asli seekh yahin milti hai: "humne ye socha tha, ye toot gaya, phir humne ye kiya".<br><br>Neeche ki list mein se hafte mein ek post padho. Shuru mein sab samajh na aaye to koi baat nahi. Course aage badhega, posts aasaan lagne lagengi.` },
    { type: 'callout', tone: 'term', title: 'Naya word: Engineering blog aur paper', html: `<strong>Engineering blog:</strong> kisi company ke engineers ke likhe articles, jaise "Discord trillions messages kaise store karta hai".<br><strong>Paper:</strong> zyada lamba, research jaisa document, aksar conference mein publish hota hai, jaise Amazon ka Dynamo paper. Thoda bhaari, lekin poori industry ki neev.` },
    { type: 'h2', text: 'Post kaise padhein' },
    { type: 'steps', items: [
      { t: 'Pehle problem padho, solution nahi', d: 'Intro padh ke ruk jao. Kagaz pe likho ki tum is problem ko kaise solve karte.' },
      { t: 'Phir poora padho, aur 3 cheezein note karo', d: '1) Kis constraint (majboori) ne unki choice force ki? 2) Kaunsa trade-off accept kiya? 3) Wo dobara karte to kya alag karte?' },
      { t: 'Memory se redraw karo', d: 'Agle din architecture diagram bina dekhe banao. Jo box bhool gaye, wahi tumhara agla revision hai.' },
    ]},
    { type: 'callout', tone: 'warn', html: `Engineering posts purani ho jaati hain. 2015 ka post us time ki sachchai hai, aaj ki nahi. Hamesha date dekho, aur ye socho ki unki problem aaj bhi wahi hai ya nahi.` },

    { type: 'h2', text: 'Newsletters aur explainers' },
    { type: 'links', items: [
      ['ByteByteGo (Alex Xu)', 'Visual, chhote explanations aur real architectures', 'https://blog.bytebytego.com'],
      ['AlgoMaster Newsletter', 'Beginner-friendly concept deep dives aur interview tips', 'https://blog.algomaster.io'],
      ['High Scalability', '"How X scaled" ka classic archive', 'http://highscalability.com'],
      ['The Pragmatic Engineer', 'Big tech systems andar se kaise chalte hain', 'https://newsletter.pragmaticengineer.com'],
      ['Martin Fowler', 'Microservices, CQRS, event sourcing, sagas', 'https://martinfowler.com'],
      ['All Things Distributed', 'Amazon CTO ka distributed systems blog (Dynamo, S3 wali team)', 'https://www.allthingsdistributed.com'],
      ['AWS Architecture Blog', 'Reference architectures', 'https://aws.amazon.com/blogs/architecture'],
    ]},
    { type: 'h2', text: 'Global engineering blogs' },
    { type: 'links', items: [
      ['Netflix TechBlog', 'Streaming at scale, chaos engineering', 'https://netflixtechblog.com'],
      ['Uber Engineering', 'H3 geo index, real-time matching', 'https://www.uber.com/blog/engineering'],
      ['Meta Engineering', 'Planet-scale caching, social graph', 'https://engineering.fb.com'],
      ['Discord', 'Trillions of chat messages', 'https://discord.com/blog'],
      ['Cloudflare', 'Networking, CDN, DDoS, edge', 'https://blog.cloudflare.com'],
      ['Slack Engineering', 'Real-time messaging, Vitess', 'https://slack.engineering'],
      ['Stripe', 'Payments reliability, idempotency', 'https://stripe.com/blog/engineering'],
      ['Dropbox Tech', 'File sync engines', 'https://dropbox.tech'],
      ['Airbnb Engineering', 'Search, payments, services mein migration', 'https://medium.com/airbnb-engineering'],
      ['LinkedIn Engineering', 'Kafka yahin bana', 'https://www.linkedin.com/blog/engineering'],
      ['Pinterest Engineering', 'Feeds, MySQL sharding, recommendations', 'https://medium.com/pinterest-engineering'],
      ['Shopify Engineering', 'Flash sales, modular monolith', 'https://shopify.engineering'],
      ['Google Research', 'GFS, MapReduce, Bigtable, Spanner ke ideas', 'https://research.google/blog'],
    ]},
    { type: 'h2', text: 'Indian engineering blogs' },
    { type: 'links', items: [
      ['Hotstar / JioHotstar', 'Crores concurrent viewers, traffic "tsunami"', 'https://blog.hotstar.com'],
      ['Swiggy Bytes', 'Dispatch, ETAs, peak-hour scaling', 'https://bytes.swiggy.com'],
      ['Zomato', 'New Year\'s Eve order peaks', 'https://blog.zomato.com'],
      ['Razorpay Engineering', 'Payments, UPI, idempotency', 'https://engineering.razorpay.com'],
      ['Zerodha Tech', 'Chhoti team, pragmatic "boring" tech', 'https://zerodha.tech'],
      ['Flipkart Tech', 'Big Billion Days traffic', 'https://blog.flipkart.tech'],
      ['PhonePe Tech', 'UPI at massive volume', 'https://tech.phonepe.com'],
    ]},
    { type: 'h2', text: 'Must-read posts aur papers' },
    { type: 'table', head: ['Title', 'Source', 'Kya sikhata hai'], rows: [
      ['Scaling Is Not An Accident; T for Tsunami', 'Hotstar', 'Live cricket ke liye pehle se scale karna (autoscaling ke bharose nahi)'],
      ['How Discord Stores Trillions of Messages', 'Discord', 'Chat storage, Cassandra se ScyllaDB, hot partitions'],
      ['H3: Uber\'s Hexagonal Hierarchical Spatial Index', 'Uber', '"Drivers near me"'],
      ['Sharding & IDs at Instagram', 'Instagram', 'Postgres sharding, time-sortable IDs'],
      ['Announcing Snowflake', 'Twitter', 'Distributed unique IDs'],
      ['Designing Robust and Predictable APIs with Idempotency', 'Stripe', 'Safe retries'],
      ['How Figma\'s Multiplayer Technology Works', 'Figma', 'Real-time collaboration, conflicts suljhana'],
      ['Rewriting the Heart of Our Sync Engine', 'Dropbox', 'File sync design'],
      ['Scaling Datastores at Slack with Vitess', 'Slack', 'MySQL sharding'],
      ['Dynamo: Amazon\'s Highly Available Key-Value Store', 'Amazon, 2007', 'Consistent hashing, quorums'],
      ['Scaling Memcache at Facebook', 'Meta, NSDI 2013', 'Caching, thundering herds'],
      ['GFS, MapReduce, Bigtable', 'Google papers', 'Storage aur batch processing ki neev'],
      ['Kafka: a Distributed Messaging System for Log Processing', 'LinkedIn, 2011', 'Queue vs log'],
    ], caption: 'Ye titles search karo; har ek roadmap ke kisi station se juda hai. Papers 2007-2013 ke hain: ideas aaj bhi zinda hain, lekin implementation details badal chuki hain.' },
    { type: 'p', html: `Shuruaat kahan se? Phase 2 ke saath Discord aur Instagram wale posts padho (chhote aur saaf). Phase 8 ke saath Hotstar, Uber aur Figma. Papers (Dynamo, Memcache) Phase 3 ke baad, jab consistency aur quorum samajh aa jayein.` },
  ],
});
